import type { InMemorySnapshotStore } from "@oh-my-pi/hashline";
import type { AgentTelemetryConfig, AgentTool } from "@oh-my-pi/pi-agent-core";
import type { ToolChoice } from "@oh-my-pi/pi-ai";
import type { PromptTemplate } from "../config/prompt-templates";
import type { Settings } from "../config/settings";
import type { GoalModeState, GoalRuntime } from "../goals";
import type { HindsightSessionState } from "../hindsight/state";
import type { PlanModeState } from "../plan-mode/state";
import type { AgentRegistry } from "../registry/agent-registry";
import type { ArtifactManager } from "../session/artifacts";
import type { ClientBridge } from "../session/client-bridge";
import type { CustomMessage } from "../session/messages";
import type { SessionStats } from "../session/agent-session";
import type { ToolChoiceQueue } from "../session/tool-choice-queue";
import type { AgentOutputManager } from "../task/output-manager";
import type { DiscoverableTool, DiscoverableToolSearchIndex } from "../tool-discovery/tool-index";
import type { EventBus } from "../utils/event-bus";
import type { WorkspaceTree } from "../workspace-tree";
import type { RuntimeTelemetrySnapshot } from "../runtime/telemetry";
import type { CheckpointState } from "./checkpoint";
import type { ConflictHistory } from "./conflict-detect";
import type { EditSafetyLog } from "./edit-safety";
import type { TodoPhase } from "./todo-write";

export type ContextFileEntry = {
	path: string;
	content: string;
	depth?: number;
};

export interface ToolSession {
	cwd: string;
	hasUI: boolean;
	skipPythonPreflight?: boolean;
	contextFiles?: ContextFileEntry[];
	workspaceTree?: WorkspaceTree;
	skills?: import("../extensibility/skills").Skill[];
	promptTemplates?: PromptTemplate[];
	enableLsp?: boolean;
	hasEditTool?: boolean;
	eventBus?: EventBus;
	outputSchema?: unknown;
	requireYieldTool?: boolean;
	taskDepth?: number;
	getEvalSessionId?: () => string | null;
	getSessionFile: () => string | null;
	getEvalKernelOwnerId?: () => string | null;
	assertEvalExecutionAllowed?: () => void;
	trackEvalExecution?<T>(execution: Promise<T>, abortController: AbortController): Promise<T>;
	getSessionId?: () => string | null;
	getHindsightSessionState?: () => HindsightSessionState | undefined;
	getAgentId?: () => string | null;
	getToolByName?: (name: string) => AgentTool | undefined;
	getActiveToolNames?: () => string[];
	getAllToolNames?: () => string[];
	getSystemPrompt?: () => string[];
	getPermissionSnapshot?: () => import("../permissions").PermissionServiceSnapshot;
	getRuntimeTelemetrySnapshot?: () => RuntimeTelemetrySnapshot | undefined;
	getSessionStats?: () => SessionStats | undefined;
	editSafetyLog?: EditSafetyLog;
	agentRegistry?: AgentRegistry;
	getArtifactsDir?: () => string | null;
	getArtifactManager?: () => ArtifactManager | null;
	allocateOutputArtifact?: (toolType: string) => Promise<{ id?: string; path?: string }>;
	getSessionSpawns: () => string | null;
	getModelString?: () => string | undefined;
	getActiveModelString?: () => string | undefined;
	authStorage?: import("../session/auth-storage").AuthStorage;
	modelRegistry?: import("../config/model-registry").ModelRegistry;
	agentOutputManager?: AgentOutputManager;
	settings: Settings;
	getPlanModeState?: () => PlanModeState | undefined;
	getGoalModeState?: () => GoalModeState | undefined;
	getGoalRuntime?: () => GoalRuntime | undefined;
	getClientBridge?: () => ClientBridge | undefined;
	getCompactContext?: () => string;
	getTodoPhases?: () => TodoPhase[];
	setTodoPhases?: (phases: TodoPhase[]) => void;
	isMCPDiscoveryEnabled?: () => boolean;
	getSelectedMCPToolNames?: () => string[];
	activateDiscoveredMCPTools?: (toolNames: string[]) => Promise<string[]>;
	isToolDiscoveryEnabled?: () => boolean;
	getDiscoverableTools?: (filter?: {
		source?: import("../tool-discovery/tool-index").DiscoverableToolSource;
	}) => DiscoverableTool[];
	getDiscoverableToolSearchIndex?: () => DiscoverableToolSearchIndex;
	getSelectedDiscoveredToolNames?: () => string[];
	activateDiscoveredTools?: (toolNames: string[]) => Promise<string[]>;
	getToolChoiceQueue?(): ToolChoiceQueue;
	buildToolChoice?(toolName: string): ToolChoice | undefined;
	steer?(message: { customType: string; content: string; details?: unknown }): void;
	peekQueueInvoker?(): ((input: unknown) => Promise<unknown> | unknown) | undefined;
	peekStandingResolveHandler?(): ((input: unknown) => Promise<unknown> | unknown) | undefined;
	setStandingResolveHandler?(handler: ((input: unknown) => Promise<unknown> | unknown) | null): void;
	getCheckpointState?: () => CheckpointState | undefined;
	setCheckpointState?: (state: CheckpointState | null) => void;
	fileSnapshotStore?: InMemorySnapshotStore;
	conflictHistory?: ConflictHistory;
	queueDeferredMessage?(message: CustomMessage): void;
	getTelemetry?: () => AgentTelemetryConfig | undefined;
}
