import Foundation

extension Notification.Name {
    static let renameActiveTab = Notification.Name("KajiRenameActiveTab")
    static let toggleThemePicker = Notification.Name("KajiToggleThemePicker")
    static let toggleSettings = Notification.Name("KajiToggleSettings")
    static let openParentAgentSettings = Notification.Name("KajiOpenParentAgentSettings")
    static let openSpeechToTextSettings = Notification.Name("KajiOpenSpeechToTextSettings")
    static let openKajiAgentSession = Notification.Name("KajiOpenKajiAgentSession")
    static let dismissSettings = Notification.Name("KajiDismissSettings")
    static let themeDidChange = Notification.Name("KajiThemeDidChange")
    static let findInTerminal = Notification.Name("KajiFindInTerminal")
    static let replaceInEditor = Notification.Name("KajiReplaceInEditor")
    static let toggleAttachedVCS = Notification.Name("KajiToggleAttachedVCS")
    static let toggleFileTree = Notification.Name("KajiToggleFileTree")
    static let toggleGlobalSearch = Notification.Name("KajiToggleGlobalSearch")
    static let toggleProblemsPanel = Notification.Name("KajiToggleProblemsPanel")
    static let openBrowserPanel = Notification.Name("KajiOpenBrowserPanel")
    static let closeBrowserPanel = Notification.Name("KajiCloseBrowserPanel")
    static let toggleBrowserPanel = Notification.Name("KajiToggleBrowserPanel")
    static let toggleFooterTerminal = Notification.Name("KajiToggleFooterTerminal")
    static let quickOpen = Notification.Name("KajiQuickOpen")
    static let commandPalette = Notification.Name("KajiCommandPalette")
    static let ask = Notification.Name("KajiAsk")
    static let openAskWithPrefill = Notification.Name("KajiOpenAskWithPrefill")
    static let agentCommandCenter = Notification.Name("KajiAgentCommandCenter")
    static let switchWorktree = Notification.Name("KajiSwitchWorktree")
    static let saveActiveEditor = Notification.Name("KajiSaveActiveEditor")
    static let goToSymbol = Notification.Name("KajiGoToSymbol")
    static let goToLine = Notification.Name("KajiGoToLine")
    static let inlineEdit = Notification.Name("KajiInlineEdit")
    static let windowFullScreenDidChange = Notification.Name("KajiWindowFullScreenDidChange")
    static let toggleSidebar = Notification.Name("KajiToggleSidebar")
    static let toggleNotificationPanel = Notification.Name("KajiToggleNotificationPanel")
    static let toggleAIUsage = Notification.Name("KajiToggleAIUsage")
    static let vcsRepoDidChange = Notification.Name("KajiVCSRepoDidChange")
    static let requestCreateWorktreeModal = Notification.Name("KajiRequestCreateWorktreeModal")
    static let requestCreateThemeModal = Notification.Name("KajiRequestCreateThemeModal")
    static let requestProjectLogoCropper = Notification.Name("KajiRequestProjectLogoCropper")
}
